### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by kunteynir** [infobloxopen/atlas-contacts-app#53]
I am getting errors: 

`# github.com/infobloxopen/atlas-contacts-app/pkg/pb
pkg/pb/contacts.override.gorm.go:174:32: too many arguments in call to DefaultListContact
        have ("context".Context, *"github.com/infobloxopen/atlas-contacts-app/vendor/github.com/jinzhu/gorm".DB, *ListContactRequest)
        want ("context".Context, *"github.com/infobloxopen/atlas-contacts-app/vendor/github.com/jinzhu/gorm".DB)
`

when trying to run app server or building docker images.

I have noticed that if I don't execute _protobuf_ target from Makefile then everything is ok.

Is it correct behaviour?

**Comment by dmacthedestroyer** [comment]
Hi @kunteynir, thanks for reporting this! We've seen this behavior a few other places in our projects, due to us making a breaking change in the [Atlas app toolkit](https://github.com/infobloxopen/atlas-app-toolkit).

Sloppy on our part -- sorry if it got in your way. We should have this fixed soon, I believe and be able to get back to you on this issue once it is.
